SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Songs;
DROP TABLE IF EXISTS Albums;
DROP TABLE IF EXISTS Artists;
DROP TABLE IF EXISTS Artist_Lists;
DROP TABLE IF EXISTS Song_Stats;
DROP TABLE IF EXISTS Playlists;

SET FOREIGN_KEY_CHECKS=1;